import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowDownToLine, Send, Loader2, TrendingUp, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Area, ComposedChart, ResponsiveContainer, Tooltip, XAxis, YAxis, Line, ReferenceLine } from "recharts";
import { useMarkets, useMarketChart } from "@/hooks/useMarkets";
import { useHoldings, useCreateTransaction } from "@/hooks/useWalletData";
import { formatFiat } from "@/lib/format";

export const Route=createFileRoute("/asset/$assetId")({component:AssetDetails});
function sma(values:number[],period:number,index:number){if(index<period-1)return null;let sum=0;for(let i=index-period+1;i<=index;i++)sum+=values[i]??0;return sum/period}
function rsi(values:number[],period=14,index:number){if(index<period)return null;let gains=0,losses=0;for(let i=index-period+1;i<=index;i++){const d=(values[i]??0)-(values[i-1]??0);if(d>=0)gains+=d;else losses-=d}if(losses===0)return 100;const rs=(gains/period)/(losses/period);return 100-(100/(1+rs))}
function AssetDetails(){
 const {assetId}=Route.useParams();const {markets,isLoading}=useMarkets();const {data:holdings=[]}=useHoldings();const [days,setDays]=useState(7);const {data:chart=[],isLoading:chartLoading}=useMarketChart(assetId,days);const createTrade=useCreateTransaction();const [side,setSide]=useState<"buy"|"sell">("buy");const [amount,setAmount]=useState("");const [showSma,setShowSma]=useState(false);const [showEma,setShowEma]=useState(false);const [showRsi,setShowRsi]=useState(true);
 const market=markets.find(a=>a.id===assetId);const balance=Number(holdings.find(h=>h.asset_id===assetId)?.balance??0);
 const chartData=useMemo(()=>{const prices=chart.map(p=>Number(p.price));let ema:number|null=null;return chart.map((point,index)=>{const price=Number(point.price);ema=ema===null?price:price*(2/6)+ema*(1-2/6);return {...point,label:new Date(point.t).toLocaleDateString(undefined,{month:"short",day:"numeric"}),sma5:sma(prices,5,index),ema5:ema,rsi14:rsi(prices,14,index)}})},[chart]);
 if(isLoading)return <main className="mx-auto max-w-lg p-5">Loading asset…</main>;if(!market)return <main className="mx-auto max-w-lg p-5">Asset not found.</main>;
 const positive=market.changePercent24h>=0;const fiatValue=Number(amount||0)*market.price;
 async function submitTrade(){const quantity=Number(amount);if(!Number.isFinite(quantity)||quantity<=0)return;try{const reference=await createTrade.mutateAsync({type:"swap",asset_id:market.id,symbol:market.symbol,amount:quantity,fiat_value:quantity*market.price,network:"Market",note:`${side.toUpperCase()} ${market.symbol}`});setAmount("");toast.success(`${side==="buy"?"Buy":"Sell"} request created`,{description:`Reference: ${reference}`})}catch(error){toast.error(error instanceof Error?error.message:"Unable to create trade request")}}
 return <main className="mx-auto max-w-lg px-4 pb-28 pt-5"><Link to="/trade" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft size={17}/>Choose another coin</Link><section className="mt-5 rounded-3xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center gap-3"><img src={market.image} alt="" className="size-12 rounded-full"/><div><h1 className="text-2xl font-semibold">{market.name}</h1><p className="text-sm text-muted-foreground">{market.symbol}/USD</p></div></div><div className="mt-7"><p className="text-4xl font-semibold tracking-tight">{formatFiat(market.price)}</p><p className={`mt-1 text-base font-medium ${positive?"text-success":"text-destructive"}`}>{positive?"▲":"▼"} {Math.abs(market.changePercent24h).toFixed(2)}% today</p></div>
 <div className="mt-5 flex items-center justify-between gap-2"><div className="flex gap-1 overflow-x-auto rounded-xl bg-secondary p-1">{[[1,"1D"],[7,"1W"],[30,"1M"],[90,"3M"]].map(([d,label])=><button key={label} type="button" onClick={()=>setDays(Number(d))} className={`rounded-lg px-3 py-1.5 text-xs whitespace-nowrap ${days===d?"bg-background font-semibold shadow-sm":"text-muted-foreground"}`}>{label}</button>)}</div><button type="button" onClick={()=>setShowRsi(v=>!v)} className={`inline-flex shrink-0 items-center gap-2 rounded-xl border px-3 py-2 text-xs font-semibold ${showRsi?"border-primary/40 bg-primary/10 text-primary":""}`}><SlidersHorizontal size={15}/>RSI</button></div>
 <div className="mt-3 flex flex-wrap gap-2 text-[11px]"><button type="button" onClick={()=>setShowSma(v=>!v)} className={`rounded-full border px-2 py-1 ${showSma?"border-primary/40 bg-primary/10":""}`}>SMA 5</button><button type="button" onClick={()=>setShowEma(v=>!v)} className={`rounded-full border px-2 py-1 ${showEma?"border-primary/40 bg-primary/10":""}`}>EMA 5</button></div>
 <div className="mt-3 h-64 rounded-2xl border border-border/70 bg-gradient-to-b from-secondary/50 to-transparent p-2 shadow-[0_18px_45px_rgba(0,0,0,0.22)]">{chartLoading?<div className="grid h-full place-items-center text-sm text-muted-foreground">Loading live chart…</div>:chartData.length>1?<ResponsiveContainer width="100%" height="100%"><ComposedChart data={chartData} margin={{top:12,right:4,left:4,bottom:0}}><defs><linearGradient id="priceFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={positive?"#22c55e":"#ef4444"} stopOpacity={0.25}/><stop offset="100%" stopColor={positive?"#22c55e":"#ef4444"} stopOpacity={0}/></linearGradient></defs><XAxis dataKey="label" tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis domain={["dataMin","dataMax"]} hide/><Tooltip formatter={(value)=>formatFiat(Number(value))} labelStyle={{fontSize:11}}/><Area type="monotone" dataKey="price" name="Price" stroke={positive?"#22c55e":"#ef4444"} strokeWidth={2.5} fill="url(#priceFill)"/>{showSma&&<Line type="monotone" dataKey="sma5" name="SMA 5" stroke="#f5c451" strokeWidth={1.5} dot={false}/>} {showEma&&<Line type="monotone" dataKey="ema5" name="EMA 5" stroke="#60a5fa" strokeWidth={1.5} dot={false}/>}</ComposedChart></ResponsiveContainer>:<div className="grid h-full place-items-center text-sm text-muted-foreground">Chart data is temporarily unavailable.</div>}</div>
 {showRsi&&chartData.length>14&&<div className="mt-2 h-28 rounded-2xl border border-border/70 bg-secondary/20 p-2"><div className="mb-1 flex justify-between px-1 text-[10px] text-muted-foreground"><span>RSI (14)</span><span>70 / 30</span></div><ResponsiveContainer width="100%" height="78%"><ComposedChart data={chartData} margin={{top:2,right:4,left:4,bottom:0}}><XAxis dataKey="label" hide/><YAxis domain={[0,100]} ticks={[30,50,70]} tick={{fontSize:9}} width={24}/><ReferenceLine y={70} strokeDasharray="3 3"/><ReferenceLine y={30} strokeDasharray="3 3"/><Line type="monotone" dataKey="rsi14" name="RSI" stroke="#a78bfa" strokeWidth={1.5} dot={false}/></ComposedChart></ResponsiveContainer></div>}
 <p className="mt-2 text-center text-xs text-muted-foreground">Live market chart • RSI and moving averages are visual indicators, not trading advice.</p><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-secondary p-4"><p className="text-xs text-muted-foreground">Your balance</p><p className="mt-1 text-lg font-semibold">{balance.toLocaleString()} {market.symbol}</p></div><div className="rounded-2xl bg-secondary p-4"><p className="text-xs text-muted-foreground">Your value</p><p className="mt-1 text-lg font-semibold">{formatFiat(balance*market.price)}</p></div></div><div className="mt-6 rounded-2xl border border-border p-4"><div className="flex items-center gap-2"><TrendingUp size={18} className="text-primary"/><h2 className="font-semibold">Trade {market.symbol}</h2></div><div className="mt-4 grid grid-cols-2 gap-2 rounded-xl bg-secondary p-1"><button type="button" onClick={()=>setSide("buy")} className={`rounded-lg px-3 py-2 text-sm font-semibold ${side==="buy"?"bg-background shadow-sm text-success":"text-muted-foreground"}`}>Buy</button><button type="button" onClick={()=>setSide("sell")} className={`rounded-lg px-3 py-2 text-sm font-semibold ${side==="sell"?"bg-background shadow-sm text-destructive":"text-muted-foreground"}`}>Sell</button></div><label className="mt-4 block text-sm font-medium">Amount<input min="0" step="any" type="number" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} className="mt-2 w-full rounded-xl border border-input bg-background px-3 py-3" placeholder={`0.00 ${market.symbol}`}/></label><p className="mt-1 text-xs text-muted-foreground">Estimated value: {formatFiat(fiatValue)}</p><button type="button" disabled={createTrade.isPending||Number(amount)<=0} onClick={()=>void submitTrade()} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 font-semibold text-primary-foreground disabled:opacity-50">{createTrade.isPending&&<Loader2 className="animate-spin" size={17}/>} {createTrade.isPending?"Submitting…":`${side==="buy"?"Buy":"Sell"} ${market.symbol}`}</button></div><div className="mt-5 grid grid-cols-2 gap-3"><Link to="/receive" className="flex items-center justify-center gap-2 rounded-xl bg-secondary px-4 py-3 text-sm font-semibold hover:bg-secondary/70"><ArrowDownToLine size={17}/>Receive</Link><Link to="/send" className="flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground hover:opacity-90"><Send size={17}/>Send</Link></div></section></main>;
}
